ENCOREC=../../../../release/encorec

STREAM_LIB=../../../../bundles/prototype/StreamLib/StreamChain

all:
	pwd
	$(ENCOREC) -I $(STREAM_LIB) streamChainTest.enc

clean:
	rm -rf streamChainTest

.PHONY: all clean
