ENCOREC=../../../../release/encorec

STREAM_LIB=../../../../bundles/standard/StreamLib/StreamChain

all:
	$(ENCOREC) -I $(STREAM_LIB) streamChainTest.enc

clean:
	rm -rf streamChainTest

.PHONY: all clean
