InputData = -I input-data/

search:
	encorec $(InputData) --run ShortestPath.enc
word:
	encorec $(InputData) --run WordCount.enc
search-compile:
	encorec $(InputData) ShortestPath.enc -o shortestpath
word-compile:
	encorec $(InputData) WordCount.enc -o wordcount
